# Generated by Django 2.1.8 on 2019-08-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profpic',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfPic',
        ),
    ]
